---
version: '3'
services:
  clamav:
    image: mkodockx/docker-clamav
    volumes:
      - ./shared:/shared

  rabbitmq:
    image: rabbitmq:3.7-rc-management
    restart: always
    volumes:
      - ./resources/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./secrets/rabbitmq-definitions.json:/run/secrets/rabbitmq-definitions.json
    ports:
      - 5673:5672
      - 15673:15672

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    volumes:
      - ./secrets/config.yml:/run/secrets/config.yml
    ports:
      - 8081:8080
    restart: always

  scanfile:
    build:
      context: .
      dockerfile: Dockerfile.scanfile
    volumes:
      - ./shared:/shared
      - ./secrets/config.yml:/run/secrets/config.yml
    restart: always

  scanurl:
    build:
      context: .
      dockerfile: Dockerfile.scanurl
    volumes:
      - ./secrets/config.yml:/run/secrets/config.yml
    restart: always
