FROM python:3.5-alpine

WORKDIR /usr/src/app

COPY . .

RUN apk update && apk upgrade && apk add --no-cache build-base cairo-dev gobject-introspection-dev libffi-dev openssl-dev && easy_install --upgrade pip && pip install --no-cache-dir --user aio-pika aiohttp "aiormq<3.0" async-timeout chardet click colorama cryptography idna keyring keyrings.alt multidict pamqp pika pyasn1 pyClamd pycrypto pygobject pyxdg PyYAML requests SecretStorage setuptools six typing-extensions urllib3 wheel yarl && python3 ./setup.py develop

#RUN apk update && apk upgrade && apk add --no-cache build-base cairo-dev gobject-introspection-dev libffi-dev openssl-dev python3-dev py3-setuptools py3-yaml py3-requests && pip install --no-cache-dir aio-pika aiohttp "aiormq<3.0" async-timeout chardet click colorama cryptography idna keyring keyrings.alt multidict pamqp pika pyasn1 pyClamd pycrypto pygobject pyxdg SecretStorage six typing-extensions urllib3 wheel yarl 

#COPY . .

#RUN python3 ./setup.py develop

ENV LC_ALL=C.UTF-8
ENV LANG C.UTF-8

CMD ["/usr/local/bin/antivirus", "scan_file"]
