FROM debian:buster-slim

WORKDIR /usr/src/app

COPY . .

RUN apt update 
RUN apt install -y python3 python3-pip python3-dev
RUN pip3 install environs
RUN pip3 install setuptools
RUN pip3 install PyYAML
RUN pip3 install pika
RUN pip3 install requests
RUN pip3 install click
RUN pip3 install pyClamd
RUN pip3 install aiohttp
RUN python3 ./setup.py develop

ENV LC_ALL=C.UTF-8
ENV LANG C.UTF-8

CMD ["/usr/local/bin/antivirus", "scan-file"]
