galaxy_info:
  role_name: antivirus_check_service
  author: Schul-Cloud Verbund
  description: role for the antivirus_check_service
  company: Schul-Cloud Verbund
  license: license (AGPLv3)
  min_ansible_version: 2.8
  galaxy_tags: []
dependencies: []
