  - name: Webserver Service
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: web-svc.yml.j2
      
  - name: Scanfile Service
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: scanfile-svc.yml.j2
      
  - name: Secred
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: secret.yml.j2
    when: ONEPASSWORD is undefined or ONEPASSWORD is defined and not ONEPASSWORD
      
  - name: Secred by 1Password
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: onepassword.yml.j2
    when: ONEPASSWORD is defined and ONEPASSWORD|bool
      
  - name: Webserver Deployment
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: web-deployment.yml.j2
      
  - name: Scanfile Deployment
    community.kubernetes.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: scanfile-deployment.yml.j2
      