  - name: Webserver Service
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: web-svc.yml.j2
      
  - name: Secret by 1Password
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: onepassword.yml.j2
    when: ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
      
  - name: Webserver Deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: web-deployment.yml.j2
      
  - name: Scanfile Deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: scanfile-deployment.yml.j2
      
