---
name: Build and push Docker Image on Main

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ scanfile, scanurl, webserver ]
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta Service Name
        id: docker_meta_img
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.service }}
          tags: |
            type=ref,event=branch,enable=false,priority=600
            type=sha,enable=true,priority=600,prefix=
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.${{ matrix.service }}
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.service }}:${{ github.sha }}
          labels: ${{ steps.docker_meta_img.outputs.labels }}

  dispatch:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_docker
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          git_ref_name="$(echo ${GITHUB_REF#refs/heads/})"
          echo "git_ref_name=$git_ref_name" >> $GITHUB_ENV
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: hpi-schul-cloud/dof_app_deploy
          event-type: dev-deploy
          client-payload: '{"branch": "${{ env.git_ref_name }}" }'
